#!/bin/bash

SERVER=$1
STATUS=""
INSTANCE_ID=$(aws ec2 describe-instances --filters Name=tag:Name,Values="$SERVER" --query 'Reservations[].Instances[].InstanceId' --output text)
while [ "$STATUS" != "running" ]; do
  STATUS=$(aws ec2 describe-instance-status --instance-id $INSTANCE_ID | jq -r ".InstanceStatuses[0].InstanceState.Name")
  if [[ "$STATUS" != "running" ]]; then
    sleep 5
  fi
done
