#!/bin/bash

DOMAIN=$1
DIR=$(dirname $0)

if [[ -z "$DOMAIN" ]]; then
  source ${DIR}/lib/prompt.sh
  prompt "Domain" "" "DOMAIN"
fi

ZONEID=$($DIR/aws-route53-zone-id $DOMAIN)
aws route53 list-resource-record-sets --hosted-zone-id $ZONEID --output table
