#!/bin/bash

if [[ -n "$1" ]]; then
  export AWS_DEFAULT_REGION=$1
fi

aws ec2 describe-instances \
  --query 'sort_by(Reservations[].Instances[].{ Name:Tags[?Key==`Name`]  | [0].Value, ID:InstanceId, State:State.Name, IP:PublicIpAddress, DNS:PublicDnsName, Type:InstanceType}, &Name)' \
  --output table
