#!/bin/bash

aws lambda list-functions \
  --query 'sort_by(Functions[].{ Name:FunctionName,Timeout:Timeout,Runtime:Runtime,MemorySize:MemorySize,Description:Description,Size:CodeSize }, &Name)' \
  --output table
