#!/bin/bash

START=$(date +%Y-%m-%d -d "10 days ago")
END=$(date +%Y-%m-%d -d "now")
aws ce get-cost-and-usage \
  --time-period Start=$START,End=$END \
  --granularity DAILY \
  --metrics "BlendedCost" \
  --query 'ResultsByTime[*].{ Start:TimePeriod.Start, Total:Total.BlendedCost.Amount }' \
  --output table
