#!/bin/bash

aws ec2 describe-instances \
  --query 'Reservations[].Instances[].{ Name:Tags[?Key==`Name`]  | [0].Value, ID:InstanceId, State:State.Name, IP:PublicIpAddress, DNS:PublicDnsName, Type:InstanceType}' \
  --output table
