#!/bin/bash

DIR=$(dirname $0)
source $DIR/lib/prompt.sh

SERVER=$1
CMD=$2
if [[ -z "$1" ]]; then
  bash $DIR/aws-ec2-list
fi

prompt "Server" "" "SERVER"
prompt "Command" "" "CMD" true

HOST=$(aws ec2 describe-instances --filters Name=tag:Name,Values="$SERVER" --query 'Reservations[].Instances[].PublicDnsName' --output text)

ssh ubuntu@$HOST $CMD
